import type { Metadata } from "next";
import classNames from "classnames";
import { Inter } from "next/font/google";
import { Header } from "@/components/common/header/Header";
import { Footer } from "@/components/common/footer/Footer";
import { QueryClientProvider } from "@/providers/query-client/QueryClientProvider";
import "@/styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={classNames(inter.className, "flex min-h-screen flex-col")}
      >
        <QueryClientProvider>
          <Header />
          <div className="flex flex-1 flex-col">{children}</div>
          <Footer />
        </QueryClientProvider>
      </body>
    </html>
  );
}
